"""Stable ATHENA SQLite schema contract and compatibility support."""

from __future__ import annotations

import sqlite3

ATHENA_APPLICATION_ID = 1_096_042_574  # ASCII "ATHN" / 0x4154484E
LEGACY_SCHEMA_VERSION = 1
KNOWLEDGE_SCHEMA_VERSION = 2
PROVENANCE_SCHEMA_VERSION = 3
MODEL_RUNS_SCHEMA_VERSION = 4
REVIEW_QUEUE_SCHEMA_VERSION = 5
MERGE_REVIEW_SCHEMA_VERSION = 6
MERGE_REVIEW_MULTI_TARGET_SCHEMA_VERSION = 7
EXTRACTION_SNAPSHOT_SCHEMA_VERSION = 8
LOCAL_FTS_SCHEMA_VERSION = 9
LOCAL_EMBEDDINGS_SCHEMA_VERSION = 10
SOURCE_CAPTURE_SCHEMA_VERSION = 11
SOURCE_REPRESENTATION_SCHEMA_VERSION = 12
SOURCE_CHUNK_PROFILE_SCHEMA_VERSION = 13
SOURCE_ANCHOR_SCHEMA_VERSION = 14
DURABLE_JOBS_SCHEMA_VERSION = 15
SOURCE_PAGE_MAP_SCHEMA_VERSION = 16
SOURCE_DOCUMENT_STRUCTURE_SCHEMA_VERSION = 17
SOURCE_ANALYSIS_SCHEMA_VERSION = 18
SOURCE_KNOWLEDGE_SCHEMA_VERSION = 19
HIERARCHICAL_SOURCE_EXTRACTION_SCHEMA_VERSION = 20
PERSONAL_MEMORY_SCHEMA_VERSION = 21
EXHAUSTIVE_RESEARCH_SCHEMA_VERSION = 22
RESEARCH_ORCHESTRATION_SCHEMA_VERSION = 23
RESEARCH_SYNTHESIS_SCHEMA_VERSION = 24
CONSOLIDATED_OPERATIONS_SCHEMA_VERSION = 25
NEWS_SYSTEM_SCHEMA_VERSION = 26
NEWS_EVENT_STRUCTURE_SCHEMA_VERSION = 27
NEWS_OPERATIONAL_SCHEMA_VERSION = 28
PRECISE_RESEARCH_PROVENANCE_SCHEMA_VERSION = 29
NEWS_EVENT_ELIGIBILITY_SCHEMA_VERSION = 30
ARCHIVE_REPLICATION_SCHEMA_VERSION = 31
PROTECTED_CONTENT_SCHEMA_VERSION = 32
PROTECTED_SOURCE_BLOB_SCHEMA_VERSION = 33
SOURCE_PROTECTION_TRANSITION_SCHEMA_VERSION = 34
BACKUP_RETENTION_SCHEMA_VERSION = 35
DELETION_LEDGER_SCHEMA_VERSION = 36
OPERATIONAL_ERROR_SANITIZATION_SCHEMA_VERSION = 37
OPERATIONAL_ERROR_PHYSICAL_CLEANUP_SCHEMA_VERSION = 38
PROTECTED_SOURCE_SEMANTIC_SCHEMA_VERSION = 39
GROUNDED_RESPONSE_RECEIPT_SCHEMA_VERSION = 40
SCHEMA_VERSION = GROUNDED_RESPONSE_RECEIPT_SCHEMA_VERSION
STORAGE_LAYOUT_VERSION = 1
BLOB_FORMAT_VERSION = 1
KNOWLEDGE_CORE_MIGRATION_ID = "0002_knowledge_core"
PROVENANCE_INPUTS_MIGRATION_ID = "0003_provenance_inputs"
MODEL_RUNS_MIGRATION_ID = "0004_model_signatures_processing_runs"
REVIEW_QUEUE_MIGRATION_ID = "0005_semantic_review_queue"
MERGE_REVIEW_MIGRATION_ID = "0006_persistent_merge_review_decisions"
MERGE_REVIEW_MULTI_TARGET_MIGRATION_ID = "0007_merge_review_multi_target_identity"
EXTRACTION_SNAPSHOT_MIGRATION_ID = "0008_frozen_extraction_snapshots"
LOCAL_FTS_SEARCH_MIGRATION_ID = "0009_local_fts_search"
LOCAL_EMBEDDINGS_MIGRATION_ID = "0010_local_embeddings"
SOURCE_CAPTURE_MIGRATION_ID = "0011_source_capture"
SOURCE_REPRESENTATION_MIGRATION_ID = "0012_source_representations"
SOURCE_CHUNK_PROFILE_MIGRATION_ID = "0013_source_chunk_profiles"
SOURCE_ANCHOR_MIGRATION_ID = "0014_source_anchors"
DURABLE_JOBS_MIGRATION_ID = "0015_durable_jobs_checkpoints"
SOURCE_PAGE_MAP_MIGRATION_ID = "0016_source_representation_page_map"
SOURCE_DOCUMENT_STRUCTURE_MIGRATION_ID = "0017_source_representation_document_structure"
SOURCE_ANALYSIS_MIGRATION_ID = "0018_hierarchical_source_analysis"
SOURCE_KNOWLEDGE_MIGRATION_ID = "0019_source_analysis_knowledge_promotion"
HIERARCHICAL_SOURCE_EXTRACTION_MIGRATION_ID = "0020_hierarchical_source_knowledge_extraction"
PERSONAL_MEMORY_MIGRATION_ID = "0021_personal_memory_core"
EXHAUSTIVE_RESEARCH_MIGRATION_ID = "0022_exhaustive_research_foundation"
RESEARCH_ORCHESTRATION_MIGRATION_ID = "0023_exhaustive_research_orchestration"
RESEARCH_SYNTHESIS_MIGRATION_ID = "0024_exhaustive_research_synthesis"
CONSOLIDATED_OPERATIONS_MIGRATION_ID = "0025_consolidated_operational_capabilities"
NEWS_SYSTEM_MIGRATION_ID = "0026_news_system"
NEWS_EVENT_STRUCTURE_MIGRATION_ID = "0027_news_event_structure"
NEWS_OPERATIONAL_MIGRATION_ID = "0028_news_operational_completion"
PRECISE_RESEARCH_PROVENANCE_MIGRATION_ID = (
    "0029_precise_research_synthesis_provenance"
)
NEWS_EVENT_ELIGIBILITY_MIGRATION_ID = (
    "0030_news_event_eligibility"
)
ARCHIVE_REPLICATION_MIGRATION_ID = (
    "0031_archive_replication_outbox"
)
PROTECTED_CONTENT_MIGRATION_ID = (
    "0032_protected_content_foundation"
)
PROTECTED_SOURCE_BLOB_MIGRATION_ID = (
    "0033_protected_source_blob_storage"
)
SOURCE_PROTECTION_TRANSITION_MIGRATION_ID = "0034_source_protection_transition"
BACKUP_RETENTION_MIGRATION_ID = "0035_backup_targets_retention"
DELETION_LEDGER_MIGRATION_ID = "0036_deletion_ledger"
OPERATIONAL_ERROR_SANITIZATION_MIGRATION_ID = (
    "0037_operational_error_sanitization"
)
OPERATIONAL_ERROR_PHYSICAL_CLEANUP_MIGRATION_ID = (
    "0038_operational_error_physical_cleanup"
)
PROTECTED_SOURCE_SEMANTIC_MIGRATION_ID = "0039_protected_source_semantic_foundation"
GROUNDED_RESPONSE_RECEIPT_MIGRATION_ID = "0040_grounded_response_receipts"



class DatabaseCompatibilityError(RuntimeError):
    """Raised when a database cannot safely be opened by this ATHENA build."""


# Preserve historical import/pickle identity through athena.storage.schema.
DatabaseCompatibilityError.__module__ = "athena.storage.schema"


def _user_tables(connection: sqlite3.Connection) -> tuple[str, ...]:
    rows = connection.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table'
          AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    return tuple(str(row[0]) for row in rows)
