from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    target = Path(path)
    text = target.read_text(encoding="utf-8")
    if text.count(old) != 1:
        raise SystemExit(f"expected exactly one match in {path}, got {text.count(old)}")
    target.write_text(text.replace(old, new, 1), encoding="utf-8")


replace_once(
    "src/athena/memory/repository.py",
    """        actor_id: uuid.UUID,\n        draft: PersonalMemoryDraft,\n        reason: str | None = None,\n    ) -> PersonalMemoryRevision:\n        self._require_unprotected_payload(draft)\n""",
    """        actor_id: uuid.UUID,\n        draft: PersonalMemoryDraft,\n        reason: str | None = None,\n        model_signature_id: uuid.UUID | None = None,\n        processing_run_id: uuid.UUID | None = None,\n    ) -> PersonalMemoryRevision:\n        self._require_unprotected_payload(draft)\n        if (model_signature_id is None) != (processing_run_id is None):\n            raise ValueError(\n                \"Personal Memory model provenance requires both model_signature_id \"\n                \"and processing_run_id.\"\n            )\n""",
)
replace_once(
    "src/athena/memory/repository.py",
    """                actor_id=actor_id,\n                created_at_us=created_at_us,\n                reason=reason,\n            )\n            self._insert_revision(\n""",
    """                actor_id=actor_id,\n                created_at_us=created_at_us,\n                reason=reason,\n                model_signature_id=model_signature_id,\n                processing_run_id=processing_run_id,\n            )\n            self._insert_revision(\n""",
)
replace_once(
    "src/athena/memory/repository.py",
    """        actor_id: uuid.UUID,\n        created_at_us: int,\n        reason: str | None,\n    ) -> None:\n        connection.execute(\n            \"\"\"\n            INSERT INTO provenance_records (\n                provenance_id, subject_entity_id, subject_revision_id, operation,\n                actor_id, created_at_us, model_signature_id, processing_run_id,\n                reason, protection_scope_id\n            ) VALUES (?, ?, ?, ?, ?, ?, NULL, NULL, ?, NULL)\n            \"\"\",\n            (\n                uuid_to_blob(provenance_id),\n                uuid_to_blob(memory_id),\n                uuid_to_blob(revision_id),\n                operation,\n                uuid_to_blob(actor_id),\n                created_at_us,\n                reason,\n            ),\n        )\n""",
    """        actor_id: uuid.UUID,\n        created_at_us: int,\n        reason: str | None,\n        model_signature_id: uuid.UUID | None = None,\n        processing_run_id: uuid.UUID | None = None,\n    ) -> None:\n        connection.execute(\n            \"\"\"\n            INSERT INTO provenance_records (\n                provenance_id, subject_entity_id, subject_revision_id, operation,\n                actor_id, created_at_us, model_signature_id, processing_run_id,\n                reason, protection_scope_id\n            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL)\n            \"\"\",\n            (\n                uuid_to_blob(provenance_id),\n                uuid_to_blob(memory_id),\n                uuid_to_blob(revision_id),\n                operation,\n                uuid_to_blob(actor_id),\n                created_at_us,\n                (\n                    uuid_to_blob(model_signature_id)\n                    if model_signature_id is not None\n                    else None\n                ),\n                uuid_to_blob(processing_run_id) if processing_run_id is not None else None,\n                reason,\n            ),\n        )\n""",
)
replace_once(
    "src/athena/memory/service.py",
    """    def remember_explicit_chat_command(\n""",
    """    def accept_model_inferred(\n        self,\n        proposal: ModelInferredMemoryProposal,\n    ) -> PersonalMemoryRevision:\n        \"\"\"Canonize one reviewed model proposal only after explicit user acceptance.\"\"\"\n        actor_id = self.chat.ensure_local_user()\n        draft = proposal.draft\n        accepted_draft = PersonalMemoryDraft(\n            memory_kind=draft.memory_kind,\n            content=draft.content,\n            scope_kind=draft.scope_kind,\n            scope_entity_id=draft.scope_entity_id,\n            learning_mode=MemoryLearningMode.MODEL_INFERRED,\n            sensitivity=draft.sensitivity,\n            confidence=draft.confidence,\n            last_confirmed_at_us=utc_now_us(),\n        )\n        return self.repository.create(\n            actor_id=actor_id,\n            draft=accepted_draft,\n            reason=\"explicit user acceptance of model-inferred Personal Memory\",\n            model_signature_id=proposal.model_signature_id,\n            processing_run_id=proposal.processing_run_id,\n        )\n\n    def remember_explicit_chat_command(\n""",
)

Path("tests/unit/test_personal_memory_review_acceptance.py").write_text(
    '''from __future__ import annotations\n\nimport uuid\n\nfrom athena.chat.repository import ChatRepository\nfrom athena.chat.service import ChatService\nfrom athena.common.ids import uuid_from_blob, uuid_to_blob\nfrom athena.memory.models import MemoryKind, MemoryLearningMode\nfrom athena.memory.repository import PersonalMemoryRepository\nfrom athena.memory.service import PersonalMemoryService\nfrom athena.storage.database import SQLiteDatabase\n\n\ndef _service(tmp_path) -> tuple[PersonalMemoryService, SQLiteDatabase]:\n    database = SQLiteDatabase(tmp_path / "athena.db")\n    database.start()\n    chat = ChatService(ChatRepository(database))\n    return PersonalMemoryService(PersonalMemoryRepository(database), chat), database\n\n\ndef test_explicit_review_accepts_inferred_memory_with_durable_model_provenance(tmp_path) -> None:\n    memory, database = _service(tmp_path)\n    model_signature_id = uuid.uuid4()\n    processing_run_id = uuid.uuid4()\n    proposal = memory.propose_model_inferred(\n        content="Prefer terse code-review summaries.",\n        memory_kind=MemoryKind.DETAIL_PREFERENCE,\n        model_signature_id=model_signature_id,\n        processing_run_id=processing_run_id,\n        confidence=0.88,\n    )\n\n    accepted = memory.accept_model_inferred(proposal)\n\n    assert accepted.payload.learning_mode is MemoryLearningMode.MODEL_INFERRED\n    assert accepted.payload.last_confirmed_at_us is not None\n    assert memory.load(accepted.memory_id).revision == accepted\n    row = database.connection.execute(\n        """\n        SELECT model_signature_id, processing_run_id\n        FROM provenance_records\n        WHERE provenance_id = ?\n        """,\n        (uuid_to_blob(accepted.provenance_id),),\n    ).fetchone()\n    assert row is not None\n    assert uuid_from_blob(bytes(row["model_signature_id"])) == model_signature_id\n    assert uuid_from_blob(bytes(row["processing_run_id"])) == processing_run_id\n\n\ndef test_review_acceptance_creates_new_memory_without_overwriting_explicit_user_memory(tmp_path) -> None:\n    memory, _ = _service(tmp_path)\n    explicit = memory.remember(\n        content="Always keep explicit preference.",\n        memory_kind=MemoryKind.DETAIL_PREFERENCE,\n    )\n    proposal = memory.propose_model_inferred(\n        content="Prefer inferred concise summaries.",\n        memory_kind=MemoryKind.DETAIL_PREFERENCE,\n        model_signature_id=uuid.uuid4(),\n        processing_run_id=uuid.uuid4(),\n        confidence=0.82,\n    )\n\n    accepted = memory.accept_model_inferred(proposal)\n\n    assert accepted.memory_id != explicit.memory_id\n    assert memory.load(explicit.memory_id).revision == explicit\n    assert memory.load(explicit.memory_id).revision.payload.learning_mode is MemoryLearningMode.EXPLICIT_USER\n    assert len(memory.list()) == 2\n''',
    encoding="utf-8",
)
