Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-PathenaWindowsSettingsPath {
    param([Parameter(Mandatory = $true)][string]$RepoRoot)
    return (Join-Path $RepoRoot ".pathena.windows.ps1")
}

function Import-PathenaWindowsSettings {
    param([Parameter(Mandatory = $true)][string]$RepoRoot)

    $settingsPath = Get-PathenaWindowsSettingsPath -RepoRoot $RepoRoot
    if (-not (Test-Path -LiteralPath $settingsPath -PathType Leaf)) {
        return $false
    }

    . $settingsPath
    return $true
}

function ConvertTo-PowerShellSingleQuotedLiteral {
    param([Parameter(Mandatory = $true)][string]$Value)
    return "'" + $Value.Replace("'", "''") + "'"
}

function Save-PathenaWindowsSettings {
    param(
        [Parameter(Mandatory = $true)][string]$RepoRoot,
        [string]$LocalRoot = "",
        [string]$LmStudioBaseUrl = ""
    )

    $settingsPath = Get-PathenaWindowsSettingsPath -RepoRoot $RepoRoot
    $lines = @(
        "# Local pATHENA Windows settings. Generated by bootstrap_windows.ps1.",
        "# This file is intentionally git-ignored and contains no model credentials."
    )

    if ($LocalRoot.Trim()) {
        $literal = ConvertTo-PowerShellSingleQuotedLiteral -Value $LocalRoot.Trim()
        $lines += "`$env:ATHENA_LOCAL_ROOT = $literal"
    }
    if ($LmStudioBaseUrl.Trim()) {
        $literal = ConvertTo-PowerShellSingleQuotedLiteral -Value $LmStudioBaseUrl.Trim()
        $lines += "`$env:ATHENA_LMSTUDIO_BASE_URL = $literal"
    }

    if ($lines.Count -eq 2) {
        if (Test-Path -LiteralPath $settingsPath) {
            Remove-Item -LiteralPath $settingsPath -Force
        }
        return
    }

    $content = ($lines -join [Environment]::NewLine) + [Environment]::NewLine
    [System.IO.File]::WriteAllText($settingsPath, $content, [System.Text.UTF8Encoding]::new($false))
}
